### ISSUE TITLE
wrap f2c c code with python

### ISSUE THREAD

**Issue by autodrive** [autodrive/Slycot#1]
* to test f2c code
* intermediate step for complete python code if desired

**Comment by autodrive** [comment]
How to : 
http://intermediate-and-advanced-software-carpentry.readthedocs.io/en/latest/c++-wrapping.html

**Comment by autodrive** [comment]
* http://www.scipy-lectures.org/advanced/interfacing_with_c/interfacing_with_c.html

**Comment by autodrive** [comment]
Cython example : _cos_cython_numpy.pyx
```
""" Example of wrapping a C function that takes C double arrays as input using
    the Numpy declarations from Cython 
    Valentin Haenel, 2.8.5.2. Numpy Support, 2.8.5. Cython, Scipy Lectures, Oct 18 2016, [Online] 
        Available: http://www.scipy-lectures.org/advanced/interfacing_with_c/interfacing_with_c.html#id13 
"""

""" Example of wrapping a C function that takes C double arrays as input using
    the Numpy declarations from Cython """

# cimport the Cython declarations for numpy
cimport numpy as np

# if you want to use the Numpy-C-API from Cython
# (not strictly necessary for this example, but good practice)
np.import_array()

# cdefine the signature of our c function
cdef extern from "cos_cython_numpy.h":
    void cos_cython_numpy_func (double * in_array, double * out_array, int size)

# create the wrapper code, with numpy type annotations
def cos_cython_numpy_py_func(np.ndarray[double, ndim=1, mode="c"] in_array not None,
                     np.ndarray[double, ndim=1, mode="c"] out_array not None):
    cos_cython_numpy_func(<double*> np.PyArray_DATA(in_array),
                <double*> np.PyArray_DATA(out_array),
                in_array.shape[0])
```

**Comment by autodrive** [comment]
## Todo : Top Level
- [ ] .pyx
- [ ] setup.py
### Todo : .pyx
- [ ] collect function definitions to one .h file, e.g., slycot-f2c.h
- [ ] make -[module name].pyx, e.g., _slycot_f2c.pyx
- [ ] copy contents of .h file to .pyx file under ```cdef extern from [module_name].h:``` with indent
- [ ] for each function, write wrapper code
#### Todo : wrapper code for each function
- [ ] Remove '_' at the end of f2c function name to make python functions name
- [ ] convert f2c function arguments
| f2c | python wrapper declaration | inside wrapper function |
| f2c                | python wrapper declaration                              | inside wrapper function              |
|:------------------:|:-------------------------------------------------------:|:------------------------------------:|
| double * @@array@@ | np.ndarray[double, ndim=1, mode="c"] @@array@@ not None | <double*> np.PyArray_DATA(@@array@@) |
| int ##size##       | <not explicitly visible>                                | @@array@@.shape[$$dim$$]             |

**Comment by autodrive** [comment]
| fortran function | # calls | call locations |
|:----------------:|:-------:|:--------------:|
| sb03md | 3 | [('control', 'mateqn.py', 75), ('control', 'mateqn.py', 257), ('control', 'statefbk.py', 370)] |
| sb04md | 1 | [('control', 'mateqn.py', 80)] |
| sg03ad | 2 | [('control', 'mateqn.py', 192), ('control', 'mateqn.py', 267)] |
| sb04qd | 1 | [('control', 'mateqn.py', 262)] |
| sb02md | 3 | [('control', 'mateqn.py', 438), ('control', 'mateqn.py', 707), ('control', 'statefbk.py', 192)] |
| sb02mt | 3 | [('control', 'mateqn.py', 443), ('control', 'mateqn.py', 712), ('control', 'statefbk.py', 193)] |
| sg02ad | 2 | [('control', 'mateqn.py', 449), ('control', 'mateqn.py', 718)] |
| ab09md | 1 | [('control', 'modelsimp.py', 260)] |
| ab09ad | 1 | [('control', 'modelsimp.py', 260)] |
| ab09nd | 1 | [('control', 'modelsimp.py', 265)] |
| sb10hd | 1 | [('control', 'robust.py', 86)] |
| sb10ad | 1 | [('control', 'robust.py', 150)] |
| sb01bd | 1 | [('control', 'statefbk.py', 76)] |
| sb03od | 1 | [('control', 'statefbk.py', 389)] |
| tb01pd | 2 | [('control', 'statesp.py', 481), ('slycot\\src', 'TD04AD.f', 394)] |
| td04ad | 3 | [('control', 'statesp.py', 660), ('control\\tests', 'slycot_convert_test.py', 56), ('control\\tests', 'slycot_convert_test.py', 115)] |
| tb04ad | 3 | [('control', 'xferfcn.py', 1101), ('control\\tests', 'slycot_convert_test.py', 56), ('control\\tests', 'slycot_convert_test.py', 115)] |
| sb02od | 1 | [('external', 'yottalab.py', 28)] |
| xerbla | 18 | [('slycot\\src', 'AB09AD.f', 303), ('slycot\\src', 'AB09MD.f', 360), ('slycot\\src', 'AB09ND.f', 381), ('slycot\\src', 'SB01BD.f', 326), ('slycot\\src', 'SB02MD.f', 395), ('slycot\\src', 'SB02MT.f', 339), ('slycot\\src', 'SB02OD.f', 559), ('slycot\\src', 'SB03MD.f', 421), ('slycot\\src', 'SB03OD.f', 385), ('slycot\\src', 'SB04MD.f', 196), ('slycot\\src', 'SB04QD.f', 201), ('slycot\\src', 'SB10AD.f', 506), ('slycot\\src', 'SB10HD.f', 312), ('slycot\\src', 'SG02AD.f', 623), ('slycot\\src', 'SG03AD.f', 459), ('slycot\\src', 'TB01PD.f', 249), ('slycot\\src', 'TB04AD.f', 320), ('slycot\\src', 'TD04AD.f', 329)] |
| tb01id | 4 | [('slycot\\src', 'AB09AD.f', 330), ('slycot\\src', 'AB09MD.f', 380), ('slycot\\src', 'AB09ND.f', 402), ('slycot\\src', 'TB01PD.f', 276)] |
| tb01wd | 1 | [('slycot\\src', 'AB09AD.f', 338)] |
| ab09ax | 2 | [('slycot\\src', 'AB09AD.f', 349), ('slycot\\src', 'AB09MD.f', 456)] |
| tb01kd | 2 | [('slycot\\src', 'AB09MD.f', 411), ('slycot\\src', 'AB09ND.f', 433)] |
| ab09bx | 1 | [('slycot\\src', 'AB09ND.f', 479)] |
| dgees | 12 | [('slycot\\src', 'SB01BD.f', 366), ('slycot\\src', 'SB02MD.f', 453), ('slycot\\src', 'SB02MD.f', 456), ('slycot\\src', 'SB02MD.f', 461), ('slycot\\src', 'SB02MD.f', 464), ('slycot\\src', 'SB02OD.f', 743), ('slycot\\src', 'SB02OD.f', 747), ('slycot\\src', 'SB03MD.f', 448), ('slycot\\src', 'SB03OD.f', 413), ('slycot\\src', 'SB04MD.f', 230), ('slycot\\src', 'SB04QD.f', 235), ('slycot\\src', 'SB10AD.f', 692)] |
| mb03qd | 1 | [('slycot\\src', 'SB01BD.f', 385)] |
| dlaset | 10 | [('slycot\\src', 'SB01BD.f', 392), ('slycot\\src', 'SB01BD.f', 756), ('slycot\\src', 'SB02MD.f', 526), ('slycot\\src', 'SB02OD.f', 821), ('slycot\\src', 'SB03OD.f', 393), ('slycot\\src', 'SB03OD.f', 653), ('slycot\\src', 'SG02AD.f', 910), ('slycot\\src', 'TB04AD.f', 346), ('slycot\\src', 'TD04AD.f', 349), ('slycot\\src', 'TD04AD.f', 356)] |
| dgemm | 17 | [('slycot\\src', 'SB01BD.f', 467), ('slycot\\src', 'SB01BD.f', 535), ('slycot\\src', 'SB01BD.f', 667), ('slycot\\src', 'SB01BD.f', 679), ('slycot\\src', 'SB01BD.f', 682), ('slycot\\src', 'SB02MT.f', 492), ('slycot\\src', 'SB02MT.f', 550), ('slycot\\src', 'SB03OD.f', 490), ('slycot\\src', 'SB03OD.f', 523), ('slycot\\src', 'SB04MD.f', 257), ('slycot\\src', 'SB04MD.f', 332), ('slycot\\src', 'SB04QD.f', 266), ('slycot\\src', 'SB04QD.f', 276), ('slycot\\src', 'SB04QD.f', 349), ('slycot\\src', 'SB04QD.f', 359), ('slycot\\src', 'SG02AD.f', 765), ('slycot\\src', 'SG02AD.f', 776)] |
| dlaexc | 2 | [('slycot\\src', 'SB01BD.f', 513), ('slycot\\src', 'SB01BD.f', 717)] |
| sb01bx | 5 | [('slycot\\src', 'SB01BD.f', 564), ('slycot\\src', 'SB01BD.f', 578), ('slycot\\src', 'SB01BD.f', 586), ('slycot\\src', 'SB01BD.f', 587), ('slycot\\src', 'SB01BD.f', 600)] |
| mb03qy | 2 | [('slycot\\src', 'SB01BD.f', 576), ('slycot\\src', 'SB01BD.f', 689)] |
| sb01by | 1 | [('slycot\\src', 'SB01BD.f', 621)] |
| drot | 3 | [('slycot\\src', 'SB01BD.f', 647), ('slycot\\src', 'SB01BD.f', 649), ('slycot\\src', 'SB01BD.f', 650)] |
| dswap | 18 | [('slycot\\src', 'SB01BD.f', 763), ('slycot\\src', 'SB01BD.f', 766), ('slycot\\src', 'SB01BD.f', 767), ('slycot\\src', 'SB02MD.f', 468), ('slycot\\src', 'SB02MD.f', 469), ('slycot\\src', 'SB02OD.f', 722), ('slycot\\src', 'SB02OD.f', 723), ('slycot\\src', 'SB02OD.f', 724), ('slycot\\src', 'SB04MD.f', 222), ('slycot\\src', 'SB04QD.f', 227), ('slycot\\src', 'SG02AD.f', 728), ('slycot\\src', 'SG02AD.f', 729), ('slycot\\src', 'SG02AD.f', 730), ('slycot\\src', 'SG02AD.f', 811), ('slycot\\src', 'SG02AD.f', 829), ('slycot\\src', 'TB04AD.f', 383), ('slycot\\src', 'TD04AD.f', 372), ('slycot\\src', 'TD04AD.f', 413)] |
| sb02mu | 1 | [('slycot\\src', 'SB02MD.f', 423)] |
| dlascl | 22 | [('slycot\\src', 'SB02MD.f', 439), ('slycot\\src', 'SB02MD.f', 441), ('slycot\\src', 'SB02MD.f', 541), ('slycot\\src', 'SB02OD.f', 632), ('slycot\\src', 'SB02OD.f', 633), ('slycot\\src', 'SB02OD.f', 635), ('slycot\\src', 'SB02OD.f', 653), ('slycot\\src', 'SB02OD.f', 654), ('slycot\\src', 'SB02OD.f', 656), ('slycot\\src', 'SB02OD.f', 684), ('slycot\\src', 'SB02OD.f', 686), ('slycot\\src', 'SB02OD.f', 689), ('slycot\\src', 'SB02OD.f', 691), ('slycot\\src', 'SB02OD.f', 693), ('slycot\\src', 'SB02OD.f', 698), ('slycot\\src', 'SG02AD.f', 680), ('slycot\\src', 'SG02AD.f', 681), ('slycot\\src', 'SG02AD.f', 683), ('slycot\\src', 'SG02AD.f', 702), ('slycot\\src', 'SG02AD.f', 703), ('slycot\\src', 'SG02AD.f', 705), ('slycot\\src', 'SG02AD.f', 924)] |
| dlacpy | 25 | [('slycot\\src', 'SB02MD.f', 489), ('slycot\\src', 'SB02OD.f', 780), ('slycot\\src', 'SB03OD.f', 492), ('slycot\\src', 'SB03OD.f', 519), ('slycot\\src', 'SB03OD.f', 526), ('slycot\\src', 'SB03OD.f', 569), ('slycot\\src', 'SB03OD.f', 583), ('slycot\\src', 'SB04MD.f', 259), ('slycot\\src', 'SB04MD.f', 334), ('slycot\\src', 'SB04QD.f', 268), ('slycot\\src', 'SB04QD.f', 278), ('slycot\\src', 'SB04QD.f', 351), ('slycot\\src', 'SB04QD.f', 361), ('slycot\\src', 'SB10AD.f', 541), ('slycot\\src', 'SB10AD.f', 543), ('slycot\\src', 'SB10AD.f', 545), ('slycot\\src', 'SB10AD.f', 592), ('slycot\\src', 'SB10AD.f', 605), ('slycot\\src', 'SB10AD.f', 690), ('slycot\\src', 'SB10HD.f', 344), ('slycot\\src', 'SB10HD.f', 345), ('slycot\\src', 'SB10HD.f', 346), ('slycot\\src', 'SG02AD.f', 767), ('slycot\\src', 'SG02AD.f', 874), ('slycot\\src', 'SG02AD.f', 875)] |
| dgetrf | 2 | [('slycot\\src', 'SB02MD.f', 490), ('slycot\\src', 'SB02OD.f', 788)] |
| dgecon | 3 | [('slycot\\src', 'SB02MD.f', 504), ('slycot\\src', 'SB02OD.f', 805), ('slycot\\src', 'SG02AD.f', 895)] |
| dcopy | 28 | [('slycot\\src', 'SB02MD.f', 518), ('slycot\\src', 'SB02MD.f', 533), ('slycot\\src', 'SB02MT.f', 378), ('slycot\\src', 'SB02MT.f', 382), ('slycot\\src', 'SB02MT.f', 388), ('slycot\\src', 'SB02MT.f', 415), ('slycot\\src', 'SB02MT.f', 419), ('slycot\\src', 'SB02MT.f', 425), ('slycot\\src', 'SB02MT.f', 508), ('slycot\\src', 'SB02MT.f', 543), ('slycot\\src', 'SB02OD.f', 752), ('slycot\\src', 'SB02OD.f', 777), ('slycot\\src', 'SB02OD.f', 846), ('slycot\\src', 'SB03MD.f', 467), ('slycot\\src', 'SB03MD.f', 490), ('slycot\\src', 'SB03OD.f', 482), ('slycot\\src', 'SB03OD.f', 498), ('slycot\\src', 'SB03OD.f', 531), ('slycot\\src', 'SB03OD.f', 576), ('slycot\\src', 'SB03OD.f', 591), ('slycot\\src', 'SB03OD.f', 600), ('slycot\\src', 'SB04MD.f', 266), ('slycot\\src', 'SB04MD.f', 340), ('slycot\\src', 'SB04QD.f', 286), ('slycot\\src', 'SB04QD.f', 369), ('slycot\\src', 'SG02AD.f', 917), ('slycot\\src', 'SG03AD.f', 535), ('slycot\\src', 'SG03AD.f', 578)] |
| dgetrs | 2 | [('slycot\\src', 'SB02MD.f', 521), ('slycot\\src', 'SB02OD.f', 816)] |
| daxpy | 3 | [('slycot\\src', 'SB02MD.f', 531), ('slycot\\src', 'SB02OD.f', 844), ('slycot\\src', 'SG02AD.f', 915)] |
| dscal | 3 | [('slycot\\src', 'SB02MD.f', 532), ('slycot\\src', 'SB02OD.f', 845), ('slycot\\src', 'SG02AD.f', 916)] |
| dpotrf | 1 | [('slycot\\src', 'SB02MT.f', 392)] |
| dpocon | 1 | [('slycot\\src', 'SB02MT.f', 398)] |
| dsytrf | 1 | [('slycot\\src', 'SB02MT.f', 434)] |
| dsycon | 1 | [('slycot\\src', 'SB02MT.f', 445)] |
| dtrsm | 2 | [('slycot\\src', 'SB02MT.f', 470), ('slycot\\src', 'SB02MT.f', 487)] |
| dsyrk | 2 | [('slycot\\src', 'SB02MT.f', 477), ('slycot\\src', 'SB02MT.f', 497)] |
| dsytrs | 2 | [('slycot\\src', 'SB02MT.f', 511), ('slycot\\src', 'SB02MT.f', 546)] |
| dgemv | 12 | [('slycot\\src', 'SB02MT.f', 521), ('slycot\\src', 'SB02MT.f', 529), ('slycot\\src', 'SB02MT.f', 559), ('slycot\\src', 'SB02MT.f', 567), ('slycot\\src', 'SB03OD.f', 499), ('slycot\\src', 'SB03OD.f', 532), ('slycot\\src', 'SB03OD.f', 592), ('slycot\\src', 'SB03OD.f', 601), ('slycot\\src', 'SB04MD.f', 264), ('slycot\\src', 'SB04MD.f', 338), ('slycot\\src', 'SB04QD.f', 284), ('slycot\\src', 'SB04QD.f', 367)] |
| sb02oy | 2 | [('slycot\\src', 'SB02OD.f', 644), ('slycot\\src', 'SG02AD.f', 693)] |
| dgges | 8 | [('slycot\\src', 'SB02OD.f', 719), ('slycot\\src', 'SB02OD.f', 726), ('slycot\\src', 'SB02OD.f', 733), ('slycot\\src', 'SB02OD.f', 737), ('slycot\\src', 'SG02AD.f', 725), ('slycot\\src', 'SG02AD.f', 732), ('slycot\\src', 'SG02AD.f', 738), ('slycot\\src', 'SG02AD.f', 742)] |
| mb01rd | 6 | [('slycot\\src', 'SB03MD.f', 463), ('slycot\\src', 'SB03MD.f', 486), ('slycot\\src', 'SG03AD.f', 526), ('slycot\\src', 'SG03AD.f', 529), ('slycot\\src', 'SG03AD.f', 570), ('slycot\\src', 'SG03AD.f', 573)] |
| sb03my | 3 | [('slycot\\src', 'SB03MD.f', 476), ('slycot\\src', 'SB03MD.f', 515), ('slycot\\src', 'SB03MD.f', 523)] |
| sb03mx | 3 | [('slycot\\src', 'SB03MD.f', 478), ('slycot\\src', 'SB03MD.f', 518), ('slycot\\src', 'SB03MD.f', 526)] |
| dlacon | 2 | [('slycot\\src', 'SB03MD.f', 511), ('slycot\\src', 'SG03AD.f', 592)] |
| dgerqf | 2 | [('slycot\\src', 'SB03OD.f', 465), ('slycot\\src', 'SB03OD.f', 614)] |
| dtrmm | 4 | [('slycot\\src', 'SB03OD.f', 486), ('slycot\\src', 'SB03OD.f', 520), ('slycot\\src', 'SB03OD.f', 570), ('slycot\\src', 'SB03OD.f', 580)] |
| dgeqrf | 3 | [('slycot\\src', 'SB03OD.f', 505), ('slycot\\src', 'SB03OD.f', 617), ('slycot\\src', 'SG02AD.f', 768)] |
| sb03ou | 1 | [('slycot\\src', 'SB03OD.f', 552)] |
| dgehrd | 2 | [('slycot\\src', 'SB04MD.f', 242), ('slycot\\src', 'SB04QD.f', 247)] |
| dormhr | 4 | [('slycot\\src', 'SB04MD.f', 251), ('slycot\\src', 'SB04MD.f', 326), ('slycot\\src', 'SB04QD.f', 256), ('slycot\\src', 'SB04QD.f', 343)] |
| sb04my | 2 | [('slycot\\src', 'SB04MD.f', 282), ('slycot\\src', 'SB04MD.f', 312)] |
| sb04mu | 1 | [('slycot\\src', 'SB04MD.f', 296)] |
| sb04qy | 2 | [('slycot\\src', 'SB04QD.f', 302), ('slycot\\src', 'SB04QD.f', 330)] |
| sb04qu | 1 | [('slycot\\src', 'SB04QD.f', 315)] |
| sb10pd | 1 | [('slycot\\src', 'SB10AD.f', 563)] |
| dgesvd | 2 | [('slycot\\src', 'SB10AD.f', 594), ('slycot\\src', 'SB10AD.f', 607)] |
| sb10qd | 2 | [('slycot\\src', 'SB10AD.f', 654), ('slycot\\src', 'SB10AD.f', 764)] |
| sb10rd | 2 | [('slycot\\src', 'SB10AD.f', 664), ('slycot\\src', 'SB10AD.f', 792)] |
| sb10ld | 2 | [('slycot\\src', 'SB10AD.f', 677), ('slycot\\src', 'SB10AD.f', 813)] |
| sb10ud | 1 | [('slycot\\src', 'SB10HD.f', 351)] |
| sb10vd | 1 | [('slycot\\src', 'SB10HD.f', 369)] |
| sb10wd | 1 | [('slycot\\src', 'SB10HD.f', 381)] |
| dorgqr | 1 | [('slycot\\src', 'SG02AD.f', 770)] |
| mb02pd | 1 | [('slycot\\src', 'SG02AD.f', 820)] |
| mb01sd | 2 | [('slycot\\src', 'SG02AD.f', 845), ('slycot\\src', 'SG02AD.f', 855)] |
| mb02vd | 1 | [('slycot\\src', 'SG02AD.f', 879)] |
| dgegs | 1 | [('slycot\\src', 'SG03AD.f', 494)] |
| mb01rw | 4 | [('slycot\\src', 'SG03AD.f', 518), ('slycot\\src', 'SG03AD.f', 521), ('slycot\\src', 'SG03AD.f', 562), ('slycot\\src', 'SG03AD.f', 565)] |
| sg03ax | 2 | [('slycot\\src', 'SG03AD.f', 543), ('slycot\\src', 'SG03AD.f', 601)] |
| sg03ay | 2 | [('slycot\\src', 'SG03AD.f', 547), ('slycot\\src', 'SG03AD.f', 606)] |
| tb01ud | 2 | [('slycot\\src', 'TB01PD.f', 294), ('slycot\\src', 'TB01PD.f', 317)] |
| ab07md | 2 | [('slycot\\src', 'TB01PD.f', 309), ('slycot\\src', 'TB04AD.f', 339)] |
| tb01xd | 3 | [('slycot\\src', 'TB01PD.f', 334), ('slycot\\src', 'TB04AD.f', 365), ('slycot\\src', 'TD04AD.f', 404)] |
| tb04ay | 1 | [('slycot\\src', 'TB04AD.f', 353)] |
| td03ay | 1 | [('slycot\\src', 'TD04AD.f', 385)] |

**Comment by kangwonlee** [comment]
[Another discussion](https://github.com/python-control/Slycot/pull/12#issuecomment-306653398) covers some of the topics

**Comment by autodrive** [comment]
Another discussion covers some of the topics

**Comment by autodrive** [comment]
@slivingston In the mean while, I plan to work on this fork.  As I mentioned, let me contact again when I think it is better prepared.

**Comment by slivingston** [comment]
good for me. I am happy to offer code review when the PR is opened upstream.
